#!/bin/bash
#Use -m to mute and -um to unmute
muted="0"
#Automatically update the kernel and program
autoupdate="0"
#Whether or not the program should warn users if the program cannot start on login
warnautostart="1"
#How many kernels should be installed before notifying users how to remove a kernel (e.g. "5" would notify on the 6th kernel installed)
maxkernelcount="5"
#Keep notifications with buttons on-screen until dismissed or not (critical / normal / low)
priority="critical"
