#!/bin/bash
checkDpkg() {
  i=0
  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
    case $((i % 4)) in
      0 ) j="-" ;;
      1 ) j="\\" ;;
      2 ) j="|" ;;
      3 ) j="/" ;;
    esac
    echo -en "\r[$j] Waiting for other software managers to finish... "
    sleep 1
    ((i=i+1))
  done
  echo -en "Done\n"
}

displayGraphics() {
  #Get display and user information
  if [[ "$DISPLAY" != "" ]]; then
    display="$DISPLAY"
    user="$USER"
  elif [[ -f "/tmp/kernel-notify.displayinfo" ]]; then
    declare "$(grep "display.*" /tmp/kernel-notify.displayinfo)" #Declare display
    declare "$(grep -v "display.*" /tmp/kernel-notify.displayinfo)" #Declare user
  else
    #No display available
    return 1
  fi

  for i in "$@"; do
    #Check if zenity is installed
    if [[ "$i" == "zenity" ]]; then
      if ! which zenity > /dev/null 2>&1; then
        echo "Zenity not installed, it is required for graphical menus"
        return 1
      fi
    fi
    #Run command on correct display with correct user
    if [[ "$i" == "launch" ]]; then
      sudo -u "$user" DISPLAY="$display" DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/"$(id -u "$user")"/bus bash -c "$1"
    fi
  done
}

getLatestKernelVersion() {
  latestVersion="$(echo $(curl -k https://www.kernel.org -s) | tr -d '\n' | awk -F'<td id="latest_button">' '{print $2}' | cut -c -70 | tr -d '\n' | awk -F'/' '{print $8}' | cut -c -70 | sed 's/linux-//g' | sed 's/.t.*//g')"
  if [[ "$checkingprecision" == "minor" ]]; then
    kernelRepoUrl="$minorversionrepo"
  elif [[ "$checkingprecision" == "major" ]]; then
    if [ "$(awk -F"." '{print NF-1}' <<< "${latestVersion}")" == "2" ]; then
      latestVersion="${latestVersion%.*}"
    fi
    kernelRepoUrl="$majorversionrepo"
  fi
  if [ "$latestVersion" == "" ]; then
    latestVersion="$(git ls-remote --refs --tags --sort="v:refname" "$kernelRepoUrl" |grep -v "[0-9]-rc" |tail -n1)"
    latestVersion="${latestVersion##*v}"
    if [ "$latestVersion" == "" ]; then
      latestVersion="x.x.x"
    fi
  fi
  echo "$latestVersion"
}

prepareVersion() {
  version=""
  for i in ${1//./ }; do
    if [[ "$i" -lt "10" ]]; then
      version+="0$i"
    else
      version+="$i"
    fi
  done
  echo "$version"
}
