#!/bin/bash
helplist=()
while read -r line; do
   helplist+=("$line")
done <<< "$(kernel-notify --help 2>/dev/null)"

for line in "${helplist[@]}"; do
  line="${line%%:*}"
  if ! echo "$line" |grep -i "kernel-notify" > /dev/null; then
    for i in $line; do
      if [[ "${#i}" -gt "3" ]] && echo "$i" |grep "^-" > /dev/null; then
        promptlist+="$i "
      fi
    done
  fi
done

complete -W "$promptlist" kernel-notify
unset helplist promptlist line i
