#!/bin/bash

_kernel_notify_config_completion() {
  #Generate configs
  local configlist
  while read -r line; do
    if echo "$line" |grep -v "Config:"> /dev/null; then
      if echo "$line" |grep -v "#"> /dev/null; then
        configlist+="${line%%=*} "
      fi
    fi
  done <<< "$(kernel-notify --config 2>/dev/null)"
  echo "$configlist"
  #grep blagh
}

_kernel_notify_arg_completion() {
  #Generate argument list
  local promptlist line i
  while read -r line; do
    line="${line%%:*}"
    for i in $line; do
      if [[ "${#i}" -gt "3" ]] && echo "$i" |grep "^-" > /dev/null; then
        promptlist+="$i "
      fi
    done
  done <<< "$(kernel-notify --help 2>/dev/null)"
  echo "$promptlist"
}

_kernel_notify_completion() {
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$prev" == "-c" ]] || [[ "$prev" == "--config" ]]; then
    local configlist
    configlist="$(_kernel_notify_config_completion)" &> /dev/null
    COMPREPLY=( $(compgen -W "$configlist" -- "$cur") )
  else
    local promptlist
    promptlist="$(_kernel_notify_arg_completion)" &> /dev/null
    COMPREPLY=( $(compgen -W "$promptlist" -- "$cur") )
  fi
  return 0
}

complete -F _kernel_notify_completion kernel-notify
