#!/bin/bash
helplist=()
while read -r line; do
   helplist+=("$line")
done <<< "$(kernel-notify --help)"

for line in "${helplist[@]}"; do
  if echo "$line" |grep ^- > /dev/null && ! echo "$line" |grep "kernel-notify" > /dev/null; then
    line="${line%%:*}"
    for i in $line; do
      if [[ "${#i}" -gt "3" ]]; then
        promptlist+="$i "
      fi
    done
  fi
done

complete -W "$promptlist" kernel-notify
unset helplist promptlist line i
