#!/bin/bash
workDir="/usr/share/kernel-notify"
cd $workDir
sudo git clone https://github.com/Dragon8oy/kernel-notify.git && cd kernel-notify && sudo dpkg --build debian && sudo dpkg -i debian.deb && cd ../ && sudo rm -rf kernel-notify
