#!/bin/bash
version="5.2"
if [ ! -d "/tmp/kernel-notify" ]; then
  mkdir /tmp/kernel-notify
fi
cd /tmp/kernel-notify
echo "Checking for updates:";
checkFiles() {
  if [ -f "kernel-notify-$latestVer""_all.deb" ]; then
    rm "kernel-notify-$latestVer""_all.deb"
  fi
  if ! ls /tmp/kernel-notify |grep -q ".*"; then
    rm -rf /tmp/kernel-notify
  else
    echo "/tmp/kernel-notify not removed as it is in use"
  fi
}
latestVer=$(curl -k -s -L https://api.github.com/repos/dragon8oy/kernel-notify/releases/latest | grep "tag_name" | cut -d v -f 2,3 | tr -d \",)
if [ "${latestVer//.}" -ne "${version//.}" ]; then
  echo "Updates are available, updating"
  curl -O -L $(curl -s -L https://api.github.com/repos/dragon8oy/kernel-notify/releases/latest |grep "browser_download_url.*deb" |cut -d : -f 2,3 |tr -d \")
  for filename in /tmp/kernel-notify/*.deb; do
    if ! file $filename | grep -q 'Debian binary package'; then
      echo "$filename: Not a Debian package"
      checkFiles
      echo "Some packages were faulty, update aborted"
      exit
    fi
  done
  sudo dpkg -i "kernel-notify-$latestVer""_all.deb"
else
  echo "Program up-to-date"
fi
checkFiles
