#!/bin/bash

#Remove notifications if unsupported
if [ ! "$(arch)" == "x86_64" ]; then
  rm /usr/share/kernel-notify/notifications
fi

#Config updater
if [ -f /usr/share/kernel-notify/config.old ] && ! diff /usr/share/kernel-notify/config /usr/share/kernel-notify/config.old > /dev/null; then
  echo "Updating config values..."
  configs=$(grep -v "#" /usr/share/kernel-notify/config.old |sed 's|=.*||')
  for i in $configs; do
    configValue=$(grep -v "#" /usr/share/kernel-notify/config.old |grep "$i" |sed 's|.*=||')
    configValue=${configValue//'"'}
    kernel-notify -c "$i" "$configValue" "silent"
  done
  echo "  ATTENTION: Config updated, run 'kernel-notify -o' to view the old config"
  #Replace deprecated config values with new values
  if [[ "$(echo -e "6.1.4\n$2" |sort -n |head -n 1)" == "6.1.4" ]]; then
    echo "Replacing deprecated config values with replacements..."
    oldConfig="$(cat /usr/share/kernel-notify/config)"
    oldConfig="${oldConfig//'"0"'/'"false"'}"
    oldConfig="${oldConfig//'"1"'/'"true"'}"
    echo "$oldConfig" > /usr/share/kernel-notify/config
    echo "Done"
  fi
fi

#Update autostart file
if [[ -f "/usr/share/kernel-notify/kernel-notify.desktop.old" ]]; then
  autostartEnabled="$(grep "X-GNOME-Autostart-enabled=" "/usr/share/kernel-notify/kernel-notify.desktop.old" |grep -v "#")"
  autostartEnabled="${autostartEnabled//X-GNOME-Autostart-enabled=}"
  if [ "$autostartEnabled" == "false" ]; then
    autostartFile="/etc/xdg/autostart/kernel-notify.desktop"
    sed "s|X-GNOME-Autostart-enabled=true|X-GNOME-Autostart-enabled=false|" "$autostartFile" > "/tmp/kernel-notify-autostart-debian.desktop.temp"
    mv "/tmp/kernel-notify-autostart-debian.desktop.temp" "$autostartFile"
  fi
fi

if kernel-notify -v; then
  echo ""; echo "Successfully installed kernel-notify"
else
  echo ""; echo "  ATTENTION: Installing kernel-notify failed"
  exit 1
fi
