#!/bin/bash
if [ -f /usr/share/kernel-notify/config ]; then
  cp /usr/share/kernel-notify/config /usr/share/kernel-notify/config.old
fi
if [ -f /etc/xdg/autostart/kernel-notify.desktop ]; then
  cp /etc/xdg/autostart/kernel-notify.desktop /usr/share/kernel-notify/kernel-notify.desktop.old
fi
