#!/bin/bash
if [ -f /usr/share/kernel-notify/config ]; then
  cp /usr/share/kernel-notify/config /usr/share/kernel-notify/config.old
fi
if [[ ! -f /etc/xdg/autostart/kernel-notify.desktop ]]; then
  touch /tmp/remove-kernel-notify-autostart
fi
