#!/bin/bash
if [ -f /etc/xdg/autostart/kernel-notify.desktop ]; then
  sudo rm /etc/xdg/autostart/kernel-notify.desktop
  echo "Removed autostart"
fi
if [ -d /usr/share/kernel-notify/ ]; then
  sudo rm -rf /usr/share/kernel-notify/
  echo "Removed program folder"
fi
