#!/bin/bash
if [ "$1" = "remove" ]; then
  if [ -f /etc/xdg/autostart/kernel-notify.desktop ]; then
    rm /etc/xdg/autostart/kernel-notify.desktop
  fi
  if [ -f /usr/share/kernel-notify/kernel-notify.desktop.old ]; then
    rm /usr/share/kernel-notify/kernel-notify.desktop.old
  fi
  if [ -f /usr/share/kernel-notify/config.old ]; then
    rm /usr/share/kernel-notify/config.old
  fi
  if [ -f /usr/share/man/man1/kernel-notify.1.gz ]; then
    rm /usr/share/man/man1/kernel-notify.1.gz
  fi
  if [ -f /usr/share/man/man1/kernel-notify.1 ]; then
    rm /usr/share/man/man1/kernel-notify.1
  fi
fi
