#!/bin/bash
if [ -f /usr/share/kernel-notify/config.old ]; then
  if ! cmp --silent /usr/share/kernel-notify/config /usr/share/kernel-notify/config.old; then
    echo "Config may have changed"
    echo "Apply any config values you wish to keep with 'kernel-notify -c CFGNAME CFGVALUE'"
    echo ""
    echo "Old values:"
    cat /usr/share/kernel-notify/config.old | cut -f1 -d"@" --zero-terminated
    echo ""
    echo ""
    echo "New values:"
    cat /usr/share/kernel-notify/config | cut -f1 -d"@" --zero-terminated
    echo ""
    echo ""
  fi
fi

kernel-notify -c installed true
echo "Successfully installed"
