#!/bin/bash

if [ -f /usr/share/kernel-notify/config.old ]; then
  echo "Apply any config values you wish to keep with 'kernel-notify -c CFGNAME CFGVALUE'"
  echo ""
  echo "Old values:"
  cat /usr/share/kernel-notify/config.old | cut -f1 -d"@" --zero-terminated
  echo ""
fi

kernel-notify -c installed true
echo "Successfully installed"
