.\" Manpage for kernel-notify.
.\" Contact stuart.a.hayhurst@gmail.com to correct errors or typos.
.TH man 1 "Built: September 2020" "Version: 6.2.1" "kernel-notify man page"
.SH NAME
kernel-notify \- Check for new kernel versions and manage installed kernels
.SH SYNOPSIS
kernel-notify [-OPTION]
.SH DESCRIPTION
kernel-notify is a mainly-bash program for checking for the latest kernel and notifying users of updates. kernel-notify can also install, update, list and remove kernels. It features a self-updater for ease-of-use.
.SH OPTIONS

.B  Program options:

-g, --gui
        Launch the program with a gui, if available

-h, --help
        Display the help page

-u, --update
        Update the program

-v, --version
        Display program version

-o, --old-config
        List old and new config values

-c, --config
        Change / read a config value
         - Use: kernel-notify --config CFGOPTION NEWCFGVALUE

--enable-autostart
        Enable kernel-notify starting on login

--disable-autostart
        Disable kernel-notify starting on login

.B  Feature options:

-L, --list-available
        List all kernels available to install

-r, --remove-kernel
        Remove a kernels from a menu

-l, --list-kernels
        List installed kernels

-a, --add-kernel
        Install a new kernel

-p, --precision
        Check either major or minor kernel updates

.SH AUTHOR
Written by Stuart Hayhurst (stuart.a.hayhurst@gmail.com)
.SH REPORTING BUGS
Report issues to: <https://github.com/Dragon8oy/kernel-notify/issues>
.br
Some bugs may already be known about or fixed in a newer build
.SH COPYRIGHT
Kernel-notify Copyright (C) 2020 Stuart Hayhurst
.br
This program comes with ABSOLUTELY NO WARRANTY.
.br
This is free software; see the source for copying conditions.
.SH SEE ALSO
zenity(1), curl(1)
.br
GitHub Source: <https://github.com/Dragon8oy/kernel-notify>
