#!/bin/bash
# shellcheck disable=SC2034
#Whether or not to send notifications for kernel and program updates
muted="0"
#Automatically update the kernel and program
autoupdate="0"
#Whether or not the program should warn users if the program cannot start on login
warnautostart="1"
#How many kernels should be installed before notifying users how to remove a kernel (e.g. "5" would notify on the 6th kernel installed)
maxkernelcount="5"
#Keep notifications with buttons on-screen until dismissed or not (critical / normal / low)
priority="critical"
#Whether to check for major and minor updates or only major version updates (minor / major)
checkingprecision="minor"
#Git repository for Linux kernel to use when checking major and minor versions (default)
minorversionrepo="git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git"
#Git repository for Linux kernel to use when only checking major versions
majorversionrepo="git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git"
