#!/bin/bash
# shellcheck disable=SC2034
#Whether or not to send notifications for kernel and program updates
muted="false"
#Automatically update the kernel
autoupdate="false"
#Show a warning if the number of kernels installed exceeds maxkernelcount
kernelcountwarning="true"
#Number of kernels installed before warning users (e.g. "5" would notify on the 6th kernel installed)
maxkernelcount="5"
#Whether or not to clean up kernel module directory after dpkg exits
kernelcleanup="true"
#Keep notifications with buttons on-screen until dismissed or not (critical / normal / low)
priority="critical"
#Whether to check for major and minor updates or only major version updates (minor / major)
checkingprecision="minor"
#Which method to use to check latest kernel version (web / git)
primarycheckingmethod="web"
#Git repository for checking major and minor versions
kernelrepourl="git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git"
