#!/bin/bash
# shellcheck disable=SC2154
checkDpkg() {
  i=0
  while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
    case $((i % 4)) in
      0 ) j="-" ;;
      1 ) j="\\" ;;
      2 ) j="|" ;;
      3 ) j="/" ;;
    esac
    echo -en "\r[$j] Waiting for other software managers to finish... "
    sleep 1
    ((i=i+1))
  done
  echo -en "Done\n"
}

checkRoot() {
  if [[ "$1" == "checksudo" ]]; then
    if command -v sudo > /dev/null 2>&1 ; then
      echo "true"
    else
      echo "false"
    fi
    return
  elif [[ "$1" == "silent" ]] ; then
    if [[ "$USER" == "root" ]]; then
      echo "true"
    else
      echo "false"
    fi
    return
  elif [[ "$USER" != "root" ]]; then
    sendError "  ATTENTION: Insufficient permission, $1" 1>&2
    exit 1
  fi
}

sendError() {
  #Output $1 to stderr
  echo -e "$1" 1>&2
}

displayGraphics() {
  #Get display and user information
  if [[ "$DISPLAY" != "" ]]; then
    display="$DISPLAY"
    user="$USER"
  elif [[ -f "/tmp/kernel-notify.displayinfo" ]]; then
    declare "$(grep "display.*" /tmp/kernel-notify.displayinfo)" #Declare display
    declare "$(grep -v "display.*" /tmp/kernel-notify.displayinfo)" #Declare user
  else
    #No display available
    return 1
  fi

  for i in "$@"; do
    #Check if zenity is installed
    if [[ "$i" == "zenity" ]]; then
      if ! command -v zenity > /dev/null 2>&1; then
        sendError "Zenity not installed, it is required for graphical menus"
        return 1
      fi
    fi
    #Run command on correct display with correct user
    if [[ "$i" == "launch" ]]; then
      if [[ "$(checkRoot "checksudo")" == "true" ]]; then
        sudo -u "$user" DISPLAY="$display" DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/"$(id -u "$user")"/bus bash -c "$1"
      else
        return 1
      fi
    fi
  done
}

getLatestKernelVersion() {
  useKernelWeb() {
    latestVersion=$(curl -k https://www.kernel.org -s) #Get webpage containing latest version
    latestVersion="$(echo "$latestVersion" | tr -d '\n')" #Remove all newlines
    latestVersion="${latestVersion#*'<td id="latest_button">'}" #Remove all html before the pattern
    latestVersion="${latestVersion%%>*}" #Remove all html after the tag with the latest version
    latestVersion="${latestVersion##*/}" #Remove all html before the filename with the latest version
    latestVersion="${latestVersion/linux-}" #Remove linux- from the filename
    latestVersion="${latestVersion%.tar*}" #Remove .tar from the filename
    echo "$latestVersion"
  }
  useKernelGit() {
    latestVersion="$(git ls-remote --refs --tags --sort="v:refname" "$kernelrepourl" 2>/dev/null |grep -v "[0-9]-rc" |tail -n1)"
    echo "${latestVersion##*v}"
  }

  getKernelVersion() {
    if [[ "$1" == "web" ]]; then
      latestVersion="$(useKernelWeb)"
    else
      latestVersion="$(useKernelGit)"
    fi
    #Correct output required precision
    if [[ "$checkingprecision" == "major" ]]; then
      if [ "$(echo "$latestVersion" |tr -cd '.' |wc -c)" == "2" ]; then
        latestVersion="${latestVersion%.*}"
      fi
    fi
    echo "$latestVersion"
  }

  #Try getKernelVersion with primary method
  latestVersion="$(getKernelVersion "$primarycheckingmethod")"
  versionExists="$(checkValidKernel "$latestVersion")"
  if [[ "$versionExists" == "invalid" ]]; then
    #Try getKernelVersion with secondary method
    if [[ "$primarycheckingmethod" != "web" ]]; then
      echo -en "\nCouldn't get latest kernel version from git, trying web..." 1>&2
      latestVersion="$(getKernelVersion "web")"
    else
      echo -en "\nCouldn't get latest kernel version from web, trying git..." 1>&2
      latestVersion="$(getKernelVersion "git")"
    fi
    #Set latestVersion to x.x.x if both methods failed
    versionExists="$(checkValidKernel "$latestVersion")"
    if [[ "$versionExists" == "invalid" ]]; then
      latestVersion="x.x.x"
    fi
  fi

  echo "$latestVersion"
}

checkValidKernel() {
  checkResult="valid"
  #Must contain a .
  if [[ ! "$1" == *"."* ]]; then
    checkResult="invalid"
  fi
  #Mustn't end or start in a .
  if [[ "${1%%-rc*}" == *"." ]] || [[ "${1%%-rc*}" == "."* ]]; then
    checkResult="invalid"
  fi
  #No group of characters can exceed a size of 3
  for i in ${1//./ }; do
    partCount=$((partCount + 1))
    if [[ "${#i}" != "1" ]] && [[ "${#i}" != "2" ]] && [[ "${#i}" != "3" ]]; then
      checkResult="invalid"
    fi
  done
  #Must only have 2 or 3 parts
  if [[ "$partCount" != "2" ]] && [[ "$partCount" != "3" ]]; then
    checkResult="invalid"
  fi
  #Mustn't contain any letters, except rc
  if [[ "${1/-rc}" =~ [a-z] ]]; then
    checkResult="invalid"
  fi
  echo "$checkResult"
}

prepareVersion() {
  version=""
  for i in ${1//./ }; do
    if [[ "$i" -lt "10" ]]; then
      version+="0$i"
    else
      version+="$i"
    fi
  done
  echo "$version"
}

sendNotification() {
  #Silence notification if program is muted
  if [[ "$muted" == "true" ]] && [[ "$4" == "mute" ]] && [[ "$5" != "silent" ]]; then
    echo "$1, $2"
  else
    #Decide whether or not to set configured priority
    if [[ "$3" == "kernel" ]] || [[ "$3" == "program" ]] || [[ "$4" == "mute" ]]; then
      displayPriority="$priority"
    fi
    #Check notifications code exists before running
    if [[ -f "$workDir/notifications" ]]; then
      if ! displayGraphics "$workDir/notifications \"$1\" \"$2\" \"kernel-notify-tux\" \"$3\" \"$4\" \"$displayPriority\" > /dev/null 2>&1 &" "launch" && [[ "$5" != "silent" ]]; then
        echo "  Notification: $1, $2"
      fi
    elif [[ "$5" != "silent" ]]; then
      echo "  Notification: $1, $2"
    fi
  fi
}
