#!/bin/bash
# shellcheck disable=SC1090
# shellcheck disable=SC2154
export workDir="/usr/share/kernel-notify"
version="6.3"

editConfig() {
  #Read arguments and input variables
  if [[ "$1" == *"="* ]]; then
    configName="${1%=*}"
    configValue="${1#*=}"
  else
    configName="$1"
    configValue="$2"
  fi

  if [ "$configName" == "" ]; then
    #Display config without #!/bin/bash
    echo "Config: $workDir/config"; echo ""; grep -v "#!/bin/bash" "$workDir/config" |grep -v "# shellcheck disable=SC2034"
  elif [ "$configValue" == "" ]; then
    #Search config for a specific config and output result
    if [[ "$3" != "silent" ]]; then
      echo "Config: $workDir/config"; echo ""
    fi
    grep "$configName" "$workDir/config"
  else
    #Search config for specific config, get the value and replace with new value
    currentConfigString="$(grep "$configName=" "$workDir/config" |grep -v "#")"
    if [[ "$currentConfigString" != "" ]]; then
      checkRoot "root is required to edit the config"
      sed "s|.*$currentConfigString.*|$configName=\"$configValue\"|" "$workDir/config" > /tmp/kernel-config.temp
      if [[ "$(cat /tmp/kernel-config.temp)" != "" ]]; then
        mv /tmp/kernel-config.temp "$workDir/config"
      else
        rm /tmp/kernel-config.temp
      fi
    else
      sendError "Invalid config name"
    fi
    #Check new config value was saved correctly
    if [[ "$(editConfig "$configName" "" "silent")" == "$configName=\"$configValue\"" ]] && [[ "$3" != "silent" ]]; then
      echo "Saved new config"
    elif [[ "$3" != "silent" ]]; then
      sendError "Failed to save new config"
    fi
  fi
}

listConfig() {
  if [ -f "$workDir/config.old" ]; then
    if ! cmp --silent "$workDir/config" "$workDir/config.old"; then
      echo "Config file has changed"
      echo "Apply old values to new config with 'kernel-notify -c CFGNAME CFGVALUE'"; echo ""
      echo "Old values:"
      cat "$workDir/config.old"; echo ""; echo ""
      echo "New values:"
      cat "$workDir/config"
    else
      echo "No change in config found"
    fi
  else
    echo "No old config file found"
  fi
}

mute() {
  #Disable autostart
  checkRoot "root is required to disable autostart"
  echo -n "Disabling kernel-notify autostart... "
  autostartFile="/etc/xdg/autostart/kernel-notify.desktop"
  #Remove .desktop file from /etc/xdg/autostart
  if [[ -f "$autostartFile" ]]; then
    rm "$autostartFile"
  fi
  #Test that the file was removed
  if [[ ! -f "$autostartFile" ]]; then
    echo "done"
  else
    echo "failed"
  fi
}

unmute() {
  #Enable autostart
  checkRoot "root is required to disable autostart"
  echo -n "Enabling kernel-notify autostart... "
  #Copy .desktop file into /etc/xdg/autostart
  autostartFile="/etc/xdg/autostart/kernel-notify.desktop"
  if [[ ! -f "$autostartFile" ]]; then
    cp "/usr/share/kernel-notify/kernel-notify.desktop" "$autostartFile"
  fi
  #Test that the file is present
  if [[ -f "$autostartFile" ]]; then
    echo "done"
  else
    sendError "failed"
  fi
}

setPrecision() {
  if [[ "$1" != "major" ]] && [[ "$1" != "minor" ]]; then
    sendError "'$1' is invalid, use either 'major' or 'minor'"
    exit 1
  else
    export checkingprecision="$1"
  fi
}

listAvailableKernels() {
  kernelList=()
  while read -r line; do
    kernelList+=("${line##*v}")
  done <<< "$(git ls-remote --refs --tags --sort="v:refname" "$kernelrepourl" |grep -v "[0-9]-rc")"
  for line in "${kernelList[@]}"; do
    echo "$line"
  done |column -x |less +G
}

automaticFeatures() {
  case $1 in
    am) mute; sendNotification "Autostart disabled" "Run 'kernel-notify --enable-autostart' to enable";;
    aa) updateKernel "automatic" "";;
  esac

  if [[ -f "/tmp/kernel-notify.displayinfo" ]]; then
    rm /tmp/kernel-notify.displayinfo
  fi
}

updateKernel() {
  clearLock() {
    if [[ -f "$lockFile" ]]; then
      rm "$lockFile"
    fi
  }

  lockFile="/tmp/kernel-notify-kernel-update.lock"
  if [[ -f "$lockFile" ]]; then
    if [[ "$1" == "automatic" ]]; then
      sendNotification "Kernel already updating" "Kernel-notify is already running, wait for it to finish"
      exit 1
    else
      echo "Kernel already updating ($lockFile is present)" 1>&2
      echo "Enter 'force' to override:"
      read -r forceUpdate
      if [[ "$forceUpdate" == "force" ]]; then
        clearLock
      else
        exit 1
      fi
    fi
  fi
  trap clearLock INT
  touch "$lockFile"

  latestVersionFull=$(getLatestKernelVersion)
  if [[ "$latestVersionFull" == "x.x.x" ]]; then
    sendNotification "Network error" "An error occured while checking latest version"
    sendError "Likely a network issue, installation cancelled"
    exit
  fi

  if [[ "$1" == "automatic" ]]; then
    "$workDir/actions" -i "$latestVersionFull" -a
    case "$?" in
      #Kernel install successful
      0) sendNotification "Kernel updated" "Run 'kernel-notify -r' to remove old kernels";;
      #Kernel install failed - missing resources
      1) sendNotification "Kernel failed to update" "Shared functions could not be found";;
      #Kernel install failed - no kernel to download / network error
      2) sendNotification "Kernel failed to update" "No kernel to download / network error";;
      #Kernel install failed - already updated
      3) sendNotification "Kernel failed to update" "Installed kernel is already the latest version";;
      #Kernel install failed - broken packages
      4) sendNotification "Kernel failed to update" "Downloaded kernel faulty";;
      #Kernel install failed - user cancelled
      5) sendNotification "Kernel failed to update" "Cancelled by user";;
      #Kernel install failed - unsupported
      6) sendNotification "Kernel failed to update" "Updating the kernel is unsupported on this system";;
      #Kernel install failed - unknown error
      7|*) sendNotification "Kernel failed to update" "Kernel failed to update for an unknown reason";;
    esac
  else
    "$workDir/actions" -i "$2"
  fi

  clearLock
  warnKernelCount
}

checkKernelVer() {
  currVersion="$1"
  latestVersionFull="$2"
  read -ra kernelList <<< "$(getKernelList)"
  if [[ "$(prepareVersion "$latestVersionFull")" != "$(prepareVersion "$currVersion")" ]]; then
    outdated="true"
    sendNotification "Kernel $(formatKernelVersion "$latestVersionFull") is available" "You are currently running Kernel $(formatKernelVersion "$currVersion")" "kernel" "mute"
  fi

  if [[ "$outdated" == "true" ]] && [[ "${kernelList[*]}" != "" ]] && echo "${kernelList[*]}" |grep "$latestVersionFull" > /dev/null 2>&1; then
    if [[ "$3" != "gui" ]]; then
      echo "Latest kernel version installed, reboot to take effect"
      outdated="false"
    fi
  fi

  if [[ "$outdated" == "true" ]] && [[ "$3" == "gui" ]]; then
    echo "Kernel: outdated" 1>&2; echo "outdated"
  elif [[ "$3" == "gui" ]]; then
    echo "Kernel: up-to-date" 1>&2; echo "up-to-date"
  fi
}

launchGui() {
  currVersion=$(uname -r | sed 's/-.*/ /g')
  latestVersion=$(getLatestKernelVersion)

  if [[ "$latestVersion" == "x.x.x" ]]; then
    sendNotification "Network error" "An error occured while checking latest version"
    exit 1
  fi

  if [[ "$(checkKernelVer "$currVersion" "$latestVersion" "gui")" == "up-to-date" ]]; then
    if ! displayGraphics 'zenity --info --window-icon=/usr/share/icons/hicolor/64x64/apps/kernel-notify-app.png --icon-name=kernel-notify --title="Kernel Updater" --text="No updates available" --width=200 --height=50' "launch" "zenity"; then
      sendNotification "Zenity issue detected" "An error occured while running zenity"
    fi
  fi
}

formatKernelVersion() {
  if [[ "${1##*.}" == "0 " ]] || [[ "${1##*.}" == "0 " ]]; then
    echo "${1%.0*}" #Remove '.0' where are kernel version ends with it
  else
    echo "${1//' '}"
  fi
}

main() {
  currVersion=$(uname -r | sed 's/-.*/ /g')
  echo -n "Checking latest version..."
  latestVersionFull=$(getLatestKernelVersion)

  if [[ "$latestVersionFull" == "x.x.x" ]]; then
    sleep 0.5; echo -ne " Error\n"; sleep 0.5
    sendNotification "Network error" "An error occured while checking latest version"
    exit 1
  else
    echo -ne " Done\n"
  fi

  if [[ "$(echo "$latestVersionFull" |tr -cd '.' |wc -c)" != "2" ]]; then
    latestVersionFull="${latestVersionFull}.0"
  fi

  echo "Latest Kernel: $(formatKernelVersion "$latestVersionFull")"
  echo "Current Kernel: $(formatKernelVersion "$currVersion")"

  #Check kernel version is outdated and notify
  checkKernelVer "$currVersion" "$latestVersionFull"

  #Check installed kernel count is below configured warning threshold
  warnKernelCount
}

#Source / check existing program files
if [[ -d "$workDir" ]] && [[ -f "$workDir/config" ]] && [[ -f "$workDir/functions" ]]; then
  source "$workDir/config"
  source "$workDir/functions"
  cd "$workDir" || exit 1
else
  sendError "Config file / kernel-notify directory missing, exiting"
  exit 1
fi

#Expand combined arguments
read -ra args <<< "$@"; argNum="0"
while [[ "$#" > "$argNum" ]]; do
  arg="${args[argNum]}"
  if [[ "$arg" = --* ]]; then
    #If the argument has 2 dashes, don't modify it
    expandedArgs+=("$arg")
  elif [[ "$arg" = -* ]]; then
    #If the argument is internal, set it to be skipped
    for i in -aa -au -am; do
      if [[ "$arg" == "$i" ]]; then
        skipArg="true"
        break
      fi
    done
    if [[ "$skipArg" == "true" ]]; then
      #Skip argument if set
      expandedArgs+=("$arg")
    else
      #Split the argument into individual letters and add to arguments array
      for splitArg in $(echo "${arg//-}" |grep -o .); do
        expandedArgs+=("-$splitArg")
      done
    fi
    skipArg="false"
  else
    #If the argument has no dashes, don't modify it
    expandedArgs+=("$arg")
  fi
  argNum=$((argNum + 1))
done

#Set variables needed for given arguments
argNum="0"
while [[ "${#expandedArgs[@]}" > "$argNum" ]]; do
  arg="${expandedArgs[argNum]}"
  case $arg in
    -p|--precision) setPrecision "${expandedArgs[((argNum + 1))]}"; expandedArgs[argNum]=""; expandedArgs[((argNum + 1))]="";;
  esac
  argNum=$((argNum + 1))
done

#Remove processed arguments from the array
for i in "${expandedArgs[@]}"; do
  if [[ "$i" != "" ]]; then
    new_array+=( "$i" )
  fi
done
expandedArgs=("${new_array[@]}")
unset args skipArg new_array

#Run given arguments
argNum="0"
while [[ "${#expandedArgs[@]}" > "$argNum" ]]; do
  arg="${expandedArgs[argNum]}"
  case $arg in
    -g|--gui) launchGui; exit;;
    -h|--help) echo "Kernel-notify Copyright (C) 2021 Stuart Hayhurst"; \
    echo "This program comes with ABSOLUTELY NO WARRANTY."; \
    echo "This is free software; see the source for copying conditions."; \
    echo ""; \
    echo "Usage: kernel-notify [-OPTIONS]"; \
    echo "Program Help:"; \
    echo "-g  | --gui         : Launch the program with a gui, if available"; \
    echo "-h  | --help        : Display this page"; \
    echo "-v  | --version     : Display program version"; \
    echo "-o  | --old-config  : List old and new config values"; \
    echo "-c  | --config      : Change / read a config value"; \
    echo "                      - kernel-notify -c configName configValue"; \
    echo "--enable-autostart  : Enable kernel-notify starting on login"; \
    echo "--disable-autostart : Disable kernel-notify starting on login"; \
    echo ""; \
    echo "Feature Help:"; \
    echo "-m  | --minimal-output : Only print the latest kernel version"; \
    echo "-L  | --list-available : List all kernels available to install"; \
    echo "-r  | --remove-kernel  : Remove kernels with a menu"; \
    echo "-l  | --list-kernels   : List installed kernels"; \
    echo "-a  | --add-kernel     : Install a new kernel"; \
    echo "-p  | --precision      : Check either major or minor kernel updates"; \
    echo ""; \
    echo "GitHub Link: https://github.com/stuarthayhurst/kernel-notify"; \
    echo "Issues: https://github.com/stuarthayhurst/kernel-notify/issues"; \
    echo "Program written by: Stuart Hayhurst"; exit;;
    -v|--version) echo "Kernel-notify version: $version"; echo ""; echo "GitHub Link: https://github.com/stuarthayhurst/kernel-notify"; echo "Program written by: Stuart Hayhurst"; exit;;
    -o|--old-config) listConfig; exit;;
    -c|--config) editConfig "${expandedArgs[((argNum + 1))]}" "${expandedArgs[((argNum + 2))]}" "${expandedArgs[((argNum + 3))]}"; exit;;
    --enable-autostart|--autostart) unmute; exit;;
    --disable-autostart) mute; exit;;
    -m|--minimal-output) echo -n "$(formatKernelVersion "$(getLatestKernelVersion)")"; exit;;
    -L|--list-available|--list-available-kernels) listAvailableKernels; exit;;
    -r|--remove-kernel|--remove-kernels) "$workDir/actions" -r "${expandedArgs[@]:1}"; exit;;
    -l|--list|--list-kernels) displayKernels; warnKernelCount; exit;;
    -a|--add-kernel) updateKernel "" "${expandedArgs[((argNum + 1))]}"; exit;;
    -am) automaticFeatures "am"; exit;;
    -aa) automaticFeatures "aa"; exit;;
    *) sendError "Unknown argument passed: $1"; "$(dirname "${BASH_SOURCE[0]}")/kernel-notify" --help; exit 1;;
  esac
  argNum=$((argNum + 1))
done

main
