#!/bin/bash
# shellcheck source=/dev/null
# shellcheck disable=SC2154
version="$1"
githubAPIString='-H "Accept: application/vnd.github.full+json"'
if [[ -f "$workDir/functions" ]]; then
  source "$workDir/functions"
else
  echo "Couldn't find common functions, exiting"
  exit 2
fi

mkdir -p "/tmp/kernel-notify"
if [ ! -w /tmp/kernel-notify ]; then
  echo "/tmp/kernel-notify is unwritable, please correct the problem and try again"
  exit 2
fi
cd /tmp/kernel-notify || exit 2
echo "Checking for updates:";

checkFiles() {
  if [ -f "$package" ]; then
    rm "$package"
  fi
  if [[ "$(ls /tmp/kernel-notify)" == "" ]]; then
    rm -rf /tmp/kernel-notify
  fi
}

latestVer=$(curl -k -s -L https://api.github.com/repos/dragon8oy/kernel-notify/releases/latest "$githubAPIString" | grep "tag_name" | cut -d v -f 2,3 | tr -d \",)

if [[ "$(dpkg -s kernel-notify 2>/dev/null)" =~ "Status: install ok installed" ]]; then
  installation="dpkg"
  package="kernel-notify-${latestVer}_all.deb"
else
  installation="source"
  package="v$latestVer.tar.gz"
fi

if [[ "${latestVer//.}" != "${version//.}" ]]; then
  echo "Updates are available, updating"
  if [ "$installation" == "dpkg" ]; then
    debDownloadLink="$(curl -s -L https://api.github.com/repos/dragon8oy/kernel-notify/releases/latest "$githubAPIString" |grep "browser_download_url.*deb" |cut -d : -f 2,3 |tr -d \")"
    curl --progress-bar -O -L "${debDownloadLink/ }"
  else
    curl --progress-bar -O -L "https://github.com/Dragon8oy/kernel-notify/archive/v$latestVer.tar.gz"
  fi

  packageType="$(file "/tmp/kernel-notify/$package")"
  if [[ ! "$packageType" =~ "gzip compressed data" ]] && [[ ! "$packageType" =~ "Debian binary package" ]]; then
    checkFiles
    echo "  ATTENTION: Downloaded update $package faulty"
    exit 2
  fi

  if [ "$installation" == "dpkg" ]; then
    checkDpkg
    sudo dpkg -i "$package"; checkFiles; exit 0
  else
    tar -xf "$package" && cd "kernel-notify-$latestVer/" && ./install.sh; checkFiles; exit 0
  fi
else
  echo "Program up-to-date"
  checkFiles; exit 1
fi
